
title: PARADISEC Workflows
description: PARADISEC technical workflows & archiving guides 
search_enabled: true
remote_theme: pmarsceill/just-the-docs
search_enabled: true
search.previews: 3
search_tokenizer_separator: /[\s/]+/
#heading_anchors: true
#color_scheme: "dark"
#theme: "just-the-docs"
